version: '3'
services:
  service:
    image: node:20
    container_name: tsukumo-front
    tty: true
    ports:
      - '3000:3000'
    networks:
      - tsukumo-nw
    volumes:
      - type: bind
        source: ../
        target: /app
    working_dir: /app
    entrypoint: "sh ./docker/entrypoint.local.sh"
    env_file:
      - ../.env.local

networks:
  tsukumo-nw:
    #    external: true
